name: dotnet test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Install dotnet-coverage
      run: dotnet tool install -g dotnet-coverage

    - name: Test with coverage
      run: dotnet-coverage collect -s coverage.settings.xml -o build/coverage/coverage.cobertura.xml -f cobertura "dotnet test --no-build --verbosity normal"

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage
      
    - name: Format check
      run: dotnet format --verify-no-changes --verbosity detailed

    - name: Build installer
      run: .\scripts\build-installer.ps1 -SkipDefenderExclusions
      shell: pwsh

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: Releases/
