name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build installer
      run: .\scripts\build-installer.ps1 -Version ${{ github.ref_name }}
      shell: pwsh

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
            Releases/*

  upload-to-s3:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Upload release to S3
        run: node scripts/upload-release-to-s3.js
        env:
          RELEASE_TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
          BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
