name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish

    - name: Create archive
      run: Compress-Archive build/publish/CoffeeUpdateClient/release/CoffeeUpdateClient.exe CoffeeUpdateClient-${{ github.ref_name }}.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
            CoffeeUpdateClient-${{ github.ref_name }}.zip