name: sync third-party addons

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  sync-addons:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: sync third-party addons
        run: node scripts/sync-third-party-addons.js
        env:
          GH_TOKEN: ${{ github.token }}
          BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
